
platform :ios, '13.0'

use_frameworks! :linkage => :static

target 'EXIAD' do
  pod "SnapKit"
  pod "Alamofire"
  
  pod "iApple", :path=>"../../"
  pod "iApple/iBase", :path=>"../../"
  pod "iApple/iView", :path=>"../../"
  pod "iApple/iAD", :path=>"../../"

#  pod "iApple", :git=>"https://gitee.com/UbunGit/iApple.git"
#  pod "iApple/iBase", :git=>"https://gitee.com/UbunGit/iApple.git"
#  pod "iApple/iView", :git=>"https://gitee.com/UbunGit/iApple.git"
#  pod "iApple/iAD", :git=>"https://gitee.com/UbunGit/iApple.git"

  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
  
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["DEVELOPMENT_TEAM"] = "A28977DMGP"
      target.build_settings(config.name)['ONLY_ACTIVE_ARCH'] = 'NO'
      
    end
  end
end
