source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks! :linkage => :static

target 'example' do


  pod "SnapKit"
  
  pod "iApple", :git=>"https://github.com/UbunGit/iApple"
  pod "iApple/iAD", :git=>"https://github.com/UbunGit/iApple"
  pod "iApple/iView", :git=>"https://github.com/UbunGit/iApple"
  pod "iApple/iRouter", :git=>"https://github.com/UbunGit/iApple"
 
end

target 'local' do

#  pod "SnapKit"
#
#  pod "iApple", :path=>"../"
#  pod "iApple/iAD", :path=>"../"
#  pod "iApple/iView", :path=>"../"
#  pod "iApple/iRouter", :path=>"../"
  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
  
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#      config.build_settings["DEVELOPMENT_TEAM"] = "QPSW766MZ5"
      target.build_settings(config.name)['ONLY_ACTIVE_ARCH'] = 'NO'
      
    end
  end
end
