
platform :ios, '13.0'

use_frameworks! :linkage => :static

target 'iSwiftUI' do

  pod "iApple/iSwiftUIKit", :path=>"../../"
  
  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
  
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    
    end
  end
end
