source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks! :linkage => :static

  

target 'Trends' do

  pod "AliyunOSSiOS"
  pod "TZImagePickerController"
  pod "IQKeyboardManager"
  pod "SDWebImageSwiftUI"
  pod "SnapKit"
  pod "iApple", :path=>"../../../../iApple"
  pod "iApple/iRandom", :path=>"../../../../iApple"

end

#target 'iHealthManage' do
#
#end



post_install do |installer|
  installer.pods_project.targets.each do |target|
  
    target.build_configurations.each do |config|
      
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["DEVELOPMENT_TEAM"] = "QPSW766MZ5"
      target.build_settings(config.name)['ONLY_ACTIVE_ARCH'] = 'NO'
      
    end
  end
end
